# Generated by Django 3.0.4 on 2020-04-22 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_complted', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('foodType', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_no', models.IntegerField()),
                ('is_ac', models.BooleanField(default=False)),
                ('is_empty', models.BooleanField(default=True)),
                ('capacity', models.IntegerField()),
                ('start_reservation_time', models.DateTimeField(null=True)),
                ('end_reservation_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.FoodItem')),
                ('food_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.CustomerOrder')),
            ],
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('order_time', models.TimeField()),
                ('total_prize', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_final_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.CustomerOrder')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Table')),
            ],
        ),
    ]
